"""Generated Codex configuration (HLD §6.5, PC-3). Pure function: the CONTROLLER calls it to
write a fresh, read-only CODEX_HOME before launch; nothing in the worker writes config.

Every key below marked [U] is a W1-O verification item on the pinned `codex` release.
"""
from __future__ import annotations

PLACEHOLDER_ENV = "VALOPS_PLACEHOLDER_KEY"  # non-secret placeholder; the broker injects the real key (PC-4)


def _q(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def config_toml(*, model: str, port: int, mcp_command: list[str]) -> str:
    args = ", ".join(_q(a) for a in mcp_command[1:])
    return f"""# GENERATED by the valops controller from the bound bundle. Read-only at runtime.
model = {_q(model)}
model_provider = "valops"
approval_policy = "never"            # non-interactive; no escalation path            [U] exact key
sandbox_mode = "read-only"           # nested inside D11; must never degrade to none   [U] PC-5
default_permissions = ":read-only"   # [E] S10
check_for_update_on_startup = false  # PC-7                                           [U]

[model_providers.valops]
name = "valops-model-broker"
base_url = "http://127.0.0.1:{port}/openai/v1"   # the broker loopback is the only route  [E] S11
env_key = "{PLACEHOLDER_ENV}"
wire_api = "responses"

[mcp_servers.valops]                  # the ONLY tool source (PC-6)                   [E] S12
command = {_q(mcp_command[0])}
args = [{args}]

[tools]
web_search = false                    # [U] exact key

[analytics]
enabled = false                       # PC-7                                           [U]
"""


def agents_md(role_prompt: str) -> str:
    """PC-3/PC-9: the only instruction file present is bundle-generated."""
    return "<!-- GENERATED from the bound policy bundle; no other instruction file is read -->\n" + role_prompt
